version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: locker
      POSTGRES_PASSWORD: locker
      POSTGRES_DB: lockerroom
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: